HIKROBOT_OPENCV_MV_INC_PATH = /opt/MVS/include
HIKROBOT_OPENCV_MV_LIB_PATH = /opt/MVS/lib/64
HIKROBOT_OPENCV_MV_LIB_LINK = MvCameraControl

HIKROBOT_OPENCV_CV_FLAGS = $(shell pkg-config opencv4 --cflags) -lopencv_core
HIKROBOT_OPENCV_MV_FLAGS = -I$(HIKROBOT_OPENCV_MV_INC_PATH) -L$(HIKROBOT_OPENCV_MV_LIB_PATH) -l$(HIKROBOT_OPENCV_MV_LIB_LINK)